spring.application.name=microkernel

spring.config.import=optional:file:.env[.properties]
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}
server.port=${CORE_SERVICE_PORT:8081}
spring.mongodb.uri=${MONGO_URI:${CLOUD_MONGO_URI:}}
management.endpoints.web.exposure.include=health,info
